#!/bin/bash
# init.sh -- generate .env and the host-side state directories.
#
# Mirrors upstream's ./init.sh, but for macOS + Apple `container`:
#   * no DBUS / PULSE host sockets (X11 is TCP, audio is optional TCP)
#   * UID/GID come straight from the macOS user
set -euo pipefail

cd "$(dirname "$0")"

mkdir -p QQ shared

# vmnet gateway as seen from inside an Apple `container` VM
HOST_GATEWAY_DEFAULT="192.168.64.1"

cat > .env <<EOF
# generated by init.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
USER_ID=$(id -u)
GROUP_ID=$(id -g)
USER_NAME=$(whoami)
HOST_GATEWAY=${HOST_GATEWAY:-$HOST_GATEWAY_DEFAULT}
X11_PORT=6000
IMAGE=mac-qq-docker:latest
CONTAINER_NAME=qq
# set to 1 to start fcitx5 inside the container
QQ_ENABLE_IME=0
EOF

echo "wrote .env:"
sed 's/^/  /' .env
echo
echo "next: ./run.sh"
